version: '2'

services:
  web:
    container_name: web
    build: ./webapp
    ports:
      - "80:80"
    volumes:
      - './webapp/src:/usr/local/apache2/htdocs/:z'

  signaling:
    container_name: signaling
    build: .
    working_dir: "/usr/src/signaling"
    ports: 
      - "3000:3000"
    volumes:
      - "./signaling:/usr/src/signaling:z"
    command: node signaling.js
